<?php
/**
 * Product list template
 */
?>

<h1>--LISTHOME--</h1>

<?php
//$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');


$_productCollection = Mage::getModel('catalog/product')->getCollection();


?>
<?php if(!$_productCollection->count()): ?>
	<p class="note-msg"><?php echo $this->__('There are no products matching the selection!') ?></p>
    <?php echo 'Count = ' . $_productCollection->count(); ?>
<!--    --><?php //var_dump( $_productCollection ); ?>
<!--    --><?php //var_dump(get_class($_productCollection)); ?>
<!--    --><?php //var_dump( $_productCollection ); ?>
<?php else: ?>
	<div class="category-products">
		<?php $_collectionSize = $_productCollection->count() ?>
		<?php $_columnCount = $this->getColumnCount(); ?>
		<?php $i=0; foreach ($_productCollection as $_product): ?>
			<?php if ($i++%$_columnCount==0): ?>
                <ul class="products-grid">
			<?php endif ?>


            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
				<?php if($_product->getRatingSummary()): ?>
					<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
				<?php endif; ?>
				<?php echo $this->getPriceHtml($_product, true) ?>
                <div class="actions">
					<?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
					<?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
					<?php endif; ?>
                    <ul class="add-to-links">
						<?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
						<?php endif; ?>
						<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
						<?php endif; ?>
                    </ul>
                </div>
            </li>


			<?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
                </ul>
			<?php endif ?>
		<?php endforeach ?>
	</div>
<?php endif; ?>
